version: '3'

services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    ports: 
      - 27017:27017

  app:
    container_name: backend-poke-api
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"